import Database from "better-sqlite3";
import path from "path";
const db = new Database(path.join(process.cwd(), "server", "database.sqlite"));
console.log('dbPath', path.join(process.cwd(), 'server', 'database.sqlite'));
console.log('user table', db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='users'").get());
console.log('social_links table', db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='social_links'").get());
console.log('users schema', JSON.stringify(db.prepare('PRAGMA table_info(users)').all(), null, 2));
console.log('products schema', JSON.stringify(db.prepare('PRAGMA table_info(products)').all(), null, 2));
console.log('all users', JSON.stringify(db.prepare('SELECT * FROM users LIMIT 5').all(), null, 2));
console.log('social links', JSON.stringify(db.prepare('SELECT * FROM social_links').all(), null, 2));
